#!/usr/bin/env sh
set -eu

MSG_FILE="$1"
MSG="$(cat "$MSG_FILE")"

# Skip commitlint for GH Actions bot and Changesets’ auto commit
if [ "${GITHUB_ACTOR:-}" = "github-actions[bot]" ]; then
  exit 0
fi
printf '%s' "$MSG" | grep -iqE '^Version Packages' && exit 0

pnpm exec commitlint --edit "$MSG_FILE"